const brands = [
  "anna sui",
  "annabelle",
  "butter london",
  "cargo cosmetics",
  "colourpop",
  "covergirl",
  "dalish",
  "dior",
  "dr. hauschka",
  "e.l.f.",
  "essie",
  "glossier",
  "iman",
  "l'oreal",
  "lotus cosmetics usa",
  "marcelle",
  "marienatie",
  "maybelline",
  "milani",
  "mineral fusion",
  "misa",
  "mistura",
  "moov",
  "nyx",
  "orly",
  "pacifica",
  "penny lane organics",
  "physicians formula",
  "pure anada",
  "rejuva minerals",
  "revlon",
  "sante",
  "sinful colours",
  "smashbox",
  "stila",
  "suncoat",
  "wet n wild",
  "zorah",
  "burt's bees",
];

export default brands;
