const brands = [
  "almaya",
  "anna sui",
  "annabelle",

  "butter london",

  "cargo cosmetics",
  "colourpop",
  "covergirl",
  "dalish",
  "dior",
  "dr. hauschka",
  "e.l.f.",
  "essie",
  "glossier",
  "iman",
  "l'oreal",
  "lotus cosmetics usa",
  "maia's mineral galaxy",
  "marcelle",
  "marienatie",
  "maybelline",
  "milani",
  "mineral fusion",
  "misa",
  "mistura",
  "moov",
  "nyx",
  "orly",
  "pacifica",
  "penny lane organics",
  "physicians formula",
  "pure anada",
  "rejuva minerals",
  "revlon",
  "sally b's skin yummies",
  "sante",
  "sinful colours",
  "smashbox",
  "stila",
  "suncoat",
  "w3llpeople",
  "wet n wild",
  "zorah",
  "zorah biocosmetiques",
];

export default brands;
